name: Francisco M. López
tagline: PhD Candidate in Developmental AI </br> Frankfurt Institute for Advanced Studies
avatar-filename: avatar.png # Change to your avatar's filename
url: fcomlop.github.io
baseurl: /
paginate: 5
paginate_path: "/projects/page:num/"

# Social Information
social:
  email: 
    visibility: true
    mail: lopez@fias.uni-frankfurt.de
  github: 
    visibility: true
    handle: fcomlop
  linkedin: 
    visibility: true
    handle: fcomlop
  twitter: 
    visibility: false
    handle: fcomlop
  scholar: 
    visibility: true
    handle: pNDeaeQAAAAJ
  orcid: 
    visibility: true
    handle: 0000-0002-9653-1740

# Collections
collections:
  experience:
    output: false
    sort_by: order
  education:
    output: false
    sort_by: order
  skills:
    output: false
    sort_by: order
  publications:
    output: true
    sort_by: year
  volunteerexperience:
    output: false
    sort_by: order
  certifications:
    output: false
    sort_by: year
  achievements:
    output: false
    sort_by: year

navigation:
- title: About
  url: /
# - title: Projects
#   url: /projects/
- title: Publications
  url: /publications
- title: CV
  url: assets/pdf/cv.pdf
- title: Strands
  url: /strands
- title: Contact
  url: /contact

include:
  - _pages

exclude:
  - readme.md

# Defaults
defaults:
  - scope:
      path: ''
      type: posts
    values:
      permalink: /:year/:title
      layout: post
      comments: false
  # - scope:
  #     path: ''
  #     type: publications
  #   values:
  #     permalink: /publications/:title
  #     layout: publication
  #     comments: false

# Disqus Comment
#disqus:
#  shortname: academic-portfolio # Change with your own disqus shortname

# Contact Form
formspree:
   endpoint: https://formspree.io/f/mzzrapob # Change with your own form's endpoint

# Google Analytics
#google_analytics: UA—XXXXXXXX-X